"""Structured schemas for Teach-the-Auditor intelligence layer.

Defines typed models for unknown network configuration commands, AI interpretations,
and human-in-the-loop teaching proposals.
Adheres to the Phoenix Protocol trust boundary:
- AI explains command meaning and security context.
- AI NEVER makes a pass/fail compliance decision.
- Rule mapping is optional; AI never invents unknown rule IDs.
- High-consequence actions require explicit human approval.
"""

from typing import Any, Dict, List, Optional, Union
from pydantic import BaseModel, Field, field_validator


# Curated, authoritative set of baseline Phoenix Protocol compliance rules
KNOWN_PHOENIX_RULES = {
    "NET-001",
    "NET-002",
    "NET-003",
    "NET-004",
    "NET-005",
    "NET-006",
    "NET-007",
    "NET-008",
    "NET-009",
    "NET-010",
}


class UnknownCommand(BaseModel):
    """Input contract for an unfamiliar or unmapped network configuration command."""

    vendor: str = Field(..., description="Device vendor (e.g., Cisco, Arista, Juniper, Palo Alto).")
    platform: str = Field(..., description="Device operating platform (e.g., IOS, EOS, JunOS, PAN-OS).")
    command: str = Field(..., min_length=1, description="The raw or normalized configuration command string.")
    context: Optional[Union[str, List[str]]] = Field(
        default=None,
        description="Surrounding configuration block lines providing context.",
    )
    source_line: Optional[int] = Field(
        default=None,
        ge=1,
        description="Optional 1-based source line number in the original configuration file.",
    )

    def to_dict(self) -> Dict[str, Any]:
        """Convert to standard dictionary representation."""
        return {
            "vendor": self.vendor,
            "platform": self.platform,
            "command": self.command,
            "context": self.context,
            "source_line": self.source_line,
        }


class CommandInterpretation(BaseModel):
    """Structured security interpretation produced by the Teach-the-Auditor agent.

    Trust boundary:
    This model captures semantic meaning, relevant security control, and confidence.
    It deliberately does NOT contain compliance verdicts ('pass'/'fail'), which are
    reserved solely for deterministic rule evaluation.
    """

    command: str = Field(..., description="The command being interpreted.")
    vendor: str = Field(..., description="Target vendor.")
    platform: str = Field(..., description="Target platform/OS.")
    meaning: str = Field(..., min_length=1, description="Concise explanation of what the command configures.")
    security_control: str = Field(
        ...,
        min_length=1,
        description="The security domain/control area (e.g. management_access, logging, encryption, authentication).",
    )
    mapped_rule_id: Optional[str] = Field(
        default=None,
        description="Authoritative Phoenix rule ID (NET-001 to NET-010) if confidently mapped; null otherwise.",
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Confidence score between 0.0 and 1.0.",
    )
    explanation: str = Field(
        ...,
        min_length=1,
        description="Rationale justifying the interpretation and any mapped rule.",
    )

    @field_validator("mapped_rule_id")
    @classmethod
    def validate_mapped_rule_id(cls, v: Optional[str]) -> Optional[str]:
        """Ensure mapped_rule_id is either None or one of the known Phoenix rule IDs.

        Never allows arbitrary or hallucinated rule IDs.
        """
        if v is None:
            return None
        cleaned = v.strip().upper()
        if not cleaned:
            return None
        if cleaned not in KNOWN_PHOENIX_RULES:
            raise ValueError(
                f"Unknown Phoenix rule ID '{v}'. Must be one of {sorted(KNOWN_PHOENIX_RULES)} or null."
            )
        return cleaned

    def to_dict(self) -> Dict[str, Any]:
        """Convert to standard dictionary representation."""
        return {
            "command": self.command,
            "vendor": self.vendor,
            "platform": self.platform,
            "meaning": self.meaning,
            "security_control": self.security_control,
            "mapped_rule_id": self.mapped_rule_id,
            "confidence": round(self.confidence, 4),
            "explanation": self.explanation,
        }


class TeachingProposal(BaseModel):
    """Proposal generated by Teach-the-Auditor requiring human review before persistence."""

    interpretation: CommandInterpretation = Field(
        ...,
        description="The structured security interpretation.",
    )
    requires_human_approval: bool = Field(
        default=True,
        description="Flag enforcing human-in-the-loop approval before knowledge persistence.",
    )
    source: str = Field(
        default="ai_agent",
        description="Origin of the interpretation ('knowledge_base' or 'ai_agent').",
    )

    def to_dict(self) -> Dict[str, Any]:
        """Convert to standard dictionary representation."""
        return {
            "interpretation": self.interpretation.to_dict(),
            "requires_human_approval": self.requires_human_approval,
            "source": self.source,
        }
