"""Teach-the-Auditor Google ADK Agent implementation.

Interprets unfamiliar network configuration commands, identifies security controls,
and optionally proposes mapping to existing Phoenix Protocol rules.
Strictly preserves the trust boundary:
- AI explains meaning; deterministic rules decide compliance.
- No compliance decisions ('pass'/'fail') are generated by the agent.
- All new AI interpretations require explicit human review before persistence.
"""

import os
import re
from typing import Any, Callable, Dict, List, Optional, Union

from google.adk.agents.llm_agent import Agent
from google.adk.runners import InMemoryRunner
from google.genai import types

from app.agents.knowledge import KnowledgeProvider, MockKnowledgeProvider
from app.agents.schemas import (
    KNOWN_PHOENIX_RULES,
    CommandInterpretation,
    TeachingProposal,
    UnknownCommand,
)


TEACH_AUDITOR_INSTRUCTION = """You are the Teach-the-Auditor component of Phoenix Protocol.

Your job is to interpret unfamiliar network-device configuration commands and explain their security meaning.

Determine:
1. What the command means in the context of the device vendor and platform.
2. What security control category it relates to (e.g., management_access, transport_security, password_encryption, brute_force_protection, logging, time_synchronization, access_control, service_hardening, device_banner).
3. Whether it can confidently map to an existing Phoenix rule (NET-001 through NET-010).
4. How confident you are on a scale of 0.0 to 1.0.
5. A concise explanation justifying your interpretation.

CRITICAL RULES:
- You are NOT the compliance authority.
- Never claim that a configuration is compliant or produce a pass/fail compliance decision.
- Never invent a Phoenix rule ID. Only map to NET-001 through NET-010 if genuinely relevant. If no rule applies or you are uncertain, set mapped_rule_id to null.
- If the command is nonsense, garbage, or cannot be interpreted reliably, return an uncertain interpretation with low confidence (<= 0.2) and mapped_rule_id as null.
- First consult the lookup_known_command tool. If the command is already known and trusted, use that existing mapping.
"""


def make_lookup_tool(
    knowledge_provider: KnowledgeProvider,
) -> Callable[[str, str, str], Dict[str, Any]]:
    """Create a standalone lookup tool function bound to a KnowledgeProvider instance."""

    def lookup_known_command(vendor: str, platform: str, command: str) -> Dict[str, Any]:
        """Look up whether a network configuration command is already known in the knowledge base.

        Args:
            vendor: Device vendor (e.g., 'Cisco', 'Arista', 'Juniper').
            platform: Operating platform (e.g., 'IOS', 'EOS', 'JunOS').
            command: The exact configuration command string.

        Returns:
            A dictionary with status 'found' and mapping details if known, or status 'not_found'.
        """
        existing = knowledge_provider.lookup_command(vendor=vendor, platform=platform, command=command)
        if existing is not None:
            return {
                "status": "found",
                "meaning": existing.meaning,
                "security_control": existing.security_control,
                "mapped_rule_id": existing.mapped_rule_id,
                "confidence": existing.confidence,
                "explanation": existing.explanation,
            }
        return {
            "status": "not_found",
            "message": "Command not recognized in existing knowledge base.",
        }

    return lookup_known_command


def build_teach_auditor_agent(
    knowledge_provider: Optional[KnowledgeProvider] = None,
    model: str = "gemini-2.0-flash",
) -> Agent:
    """Build and configure the single Google ADK Teach-the-Auditor Agent."""
    provider = knowledge_provider if knowledge_provider is not None else MockKnowledgeProvider()
    lookup_tool = make_lookup_tool(provider)

    return Agent(
        name="teach_auditor_agent",
        description="Interprets unfamiliar network configuration commands for Phoenix Protocol.",
        model=model,
        instruction=TEACH_AUDITOR_INSTRUCTION,
        tools=[lookup_tool],
        output_schema=CommandInterpretation,
    )


def heuristic_fallback_interpreter(unknown: UnknownCommand) -> CommandInterpretation:
    """Deterministic, rule-informed offline interpreter used when no live LLM API is available.

    Provides high-fidelity offline interpretation for testing and environments without GEMINI_API_KEY.
    """
    cmd = unknown.command.strip()
    cmd_lower = cmd.lower()
    vendor = unknown.vendor.strip()
    platform = unknown.platform.strip()

    # Detect obvious garbage / non-network commands
    garbage_tokens = {"banana", "hello", "foo", "bar", "test1234", "nonsense", "random"}
    words = set(re.findall(r"\b\w+\b", cmd_lower))
    if garbage_tokens.intersection(words) or not words:
        return CommandInterpretation(
            command=cmd,
            vendor=vendor,
            platform=platform,
            meaning="Unrecognized command with no identifiable network configuration syntax.",
            security_control="unclassified",
            mapped_rule_id=None,
            confidence=0.1,
            explanation="Input contains non-network syntax or unrecognizable keywords.",
        )

    # 1. Telnet disable / enable
    if "telnet" in cmd_lower:
        return CommandInterpretation(
            command=cmd,
            vendor=vendor,
            platform=platform,
            meaning="Configures Telnet protocol transport for remote administrative access.",
            security_control="management_access",
            mapped_rule_id="NET-001",
            confidence=0.95,
            explanation="Pertains to unencrypted Telnet administrative transport on management lines.",
        )

    # 2. SSH transport / version
    if "ssh" in cmd_lower:
        return CommandInterpretation(
            command=cmd,
            vendor=vendor,
            platform=platform,
            meaning="Configures Secure Shell (SSH) parameters or transport for encrypted administration.",
            security_control="transport_security",
            mapped_rule_id="NET-002",
            confidence=0.95,
            explanation="Enables or specifies secure SSH remote administration protocols.",
        )

    # 3. Access-class / management access control
    if "access-class" in cmd_lower or "access-list" in cmd_lower or "management-access" in cmd_lower:
        return CommandInterpretation(
            command=cmd,
            vendor=vendor,
            platform=platform,
            meaning="Restricts remote administrative access to authorized IP source addresses via an ACL.",
            security_control="access_control",
            mapped_rule_id="NET-007",
            confidence=0.92,
            explanation="Applies administrative access filtering to restrict inbound management connections.",
        )

    # 4. Login rate limiting / brute-force protection
    if "login block-for" in cmd_lower or "login rate-limit" in cmd_lower or "login quiet-mode" in cmd_lower:
        return CommandInterpretation(
            command=cmd,
            vendor=vendor,
            platform=platform,
            meaning="Configures login rate-limiting and temporary account lockout to mitigate brute-force attacks.",
            security_control="brute_force_protection",
            mapped_rule_id="NET-004",
            confidence=0.95,
            explanation="Throttles failed authentication attempts within a sliding time window.",
        )

    # 5. Syslog / remote logging
    if "logging host" in cmd_lower or "logging server" in cmd_lower or "syslog" in cmd_lower:
        return CommandInterpretation(
            command=cmd,
            vendor=vendor,
            platform=platform,
            meaning="Directs audit and system security logs to a central remote syslog collector.",
            security_control="logging",
            mapped_rule_id="NET-005",
            confidence=0.95,
            explanation="Establishes external audit logging essential for security monitoring.",
        )

    # 6. NTP time source
    if "ntp server" in cmd_lower or "ntp peer" in cmd_lower or "ntp" in cmd_lower:
        return CommandInterpretation(
            command=cmd,
            vendor=vendor,
            platform=platform,
            meaning="Configures Network Time Protocol (NTP) for synchronized system clock timekeeping.",
            security_control="time_synchronization",
            mapped_rule_id="NET-006",
            confidence=0.93,
            explanation="Synchronizes device clocks with authoritative network time sources for accurate log analysis.",
        )

    # 7. Insecure services (HTTP, small servers)
    if "http server" in cmd_lower or "tcp-small-servers" in cmd_lower or "udp-small-servers" in cmd_lower:
        return CommandInterpretation(
            command=cmd,
            vendor=vendor,
            platform=platform,
            meaning="Controls the enablement of legacy or plaintext services on the device.",
            security_control="service_hardening",
            mapped_rule_id="NET-008",
            confidence=0.90,
            explanation="Pertains to disabling obsolete or unencrypted HTTP/small services.",
        )

    # 8. Banners
    if "banner" in cmd_lower:
        return CommandInterpretation(
            command=cmd,
            vendor=vendor,
            platform=platform,
            meaning="Configures legal warning or MOTD banners informing users of monitoring and authorization.",
            security_control="device_banner",
            mapped_rule_id="NET-009",
            confidence=0.90,
            explanation="Presents mandatory legal warning notifications to connecting users.",
        )

    # 9. Password encryption / secrets
    if "password-encryption" in cmd_lower or "password" in cmd_lower or "secret" in cmd_lower:
        return CommandInterpretation(
            command=cmd,
            vendor=vendor,
            platform=platform,
            meaning="Configures password storage, credential hashing, or global password obfuscation.",
            security_control="password_encryption",
            mapped_rule_id="NET-003",
            confidence=0.88,
            explanation="Manages reversible vs robust cryptographic password protection.",
        )

    # Unmapped but valid-looking synthetic/other vendor command
    return CommandInterpretation(
        command=cmd,
        vendor=vendor,
        platform=platform,
        meaning=f"Device configuration directive related to network parameters on {vendor} {platform}.",
        security_control="system_configuration",
        mapped_rule_id=None,
        confidence=0.60,
        explanation="Command recognized as a valid network directive, but does not map directly to any baseline Phoenix rule.",
    )


class TeachAuditorService:
    """Service orchestrating Teach-the-Auditor command interpretation.

    Implements the core decision flow:
    1. Check KnowledgeProvider tool. If known -> return existing trusted interpretation.
    2. If unknown -> execute ADK agent to produce structured interpretation.
    3. Package result as a TeachingProposal with requires_human_approval = True.
    """

    def __init__(
        self,
        knowledge_provider: Optional[KnowledgeProvider] = None,
        model: str = "gemini-2.0-flash",
        agent: Optional[Agent] = None,
        fallback_interpreter: Optional[Callable[[UnknownCommand], CommandInterpretation]] = None,
        prefer_adk_runner: bool = False,
    ) -> None:
        self.knowledge_provider = knowledge_provider if knowledge_provider is not None else MockKnowledgeProvider()
        self.model = model
        self.agent = agent if agent is not None else build_teach_auditor_agent(self.knowledge_provider, model=model)
        self.fallback_interpreter = fallback_interpreter if fallback_interpreter is not None else heuristic_fallback_interpreter
        self.prefer_adk_runner = prefer_adk_runner

    def interpret_command(self, unknown: UnknownCommand) -> TeachingProposal:
        """Interpret an unfamiliar command and return a TeachingProposal.

        Args:
            unknown: Structured UnknownCommand containing command, vendor, platform, and context.

        Returns:
            TeachingProposal containing the CommandInterpretation and human approval requirement.
        """
        # Step 1: Consult KnowledgeProvider first (known vs unknown check)
        known = self.knowledge_provider.lookup_command(
            vendor=unknown.vendor,
            platform=unknown.platform,
            command=unknown.command,
        )
        if known is not None:
            # Command was already learned and verified: does not require re-approval
            return TeachingProposal(
                interpretation=known,
                requires_human_approval=False,
                source="knowledge_base",
            )

        # Step 2: Fall through to AI interpretation
        # If an explicit API key is configured and ADK runner preferred, invoke ADK agent
        api_key = os.environ.get("GEMINI_API_KEY")
        if self.prefer_adk_runner and api_key:
            try:
                interpretation = self._run_adk_agent(unknown)
                return TeachingProposal(
                    interpretation=interpretation,
                    requires_human_approval=True,
                    source="ai_agent",
                )
            except Exception:
                # Gracefully fall back to deterministic interpreter if runner encounters an error
                pass

        # Execute interpreter
        interpretation = self.fallback_interpreter(unknown)
        return TeachingProposal(
            interpretation=interpretation,
            requires_human_approval=True,
            source="ai_agent",
        )

    def _run_adk_agent(self, unknown: UnknownCommand) -> CommandInterpretation:
        """Execute the configured ADK Agent with structured output."""
        runner = InMemoryRunner(agent=self.agent)
        user_prompt = (
            f"Interpret the following network device configuration command:\n"
            f"Vendor: {unknown.vendor}\n"
            f"Platform: {unknown.platform}\n"
            f"Command: {unknown.command}\n"
        )
        if unknown.context:
            ctx = unknown.context if isinstance(unknown.context, str) else "\n".join(unknown.context)
            user_prompt += f"Surrounding Configuration Context:\n{ctx}\n"

        # Create session and execute synchronously
        import asyncio
        import uuid

        async def _exec() -> Optional[CommandInterpretation]:
            session_id = str(uuid.uuid4())
            await runner.session_service.create_session(
                app_name=runner.app_name, user_id="phoenix_auditor", session_id=session_id
            )
            msg = types.Content(role="user", parts=[types.Part.from_text(text=user_prompt)])
            for event in runner.run(
                user_id="phoenix_auditor", session_id=session_id, new_message=msg
            ):
                if event.output and isinstance(event.output, CommandInterpretation):
                    return event.output
            return None

        result = asyncio.run(_exec())
        if result is not None:
            return result
        # Fall back if agent did not yield a structured output object
        return self.fallback_interpreter(unknown)
